version: 0.2.0

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

#build from the docs directory with sphinx
sphinx:
  configuration: docs/conf.py

# set requirements
python:
  install:
    - requirements: docs/requirements.txt